project_id = "bxrxrdloufobxdkdehtc"

[functions.ai-chat]
verify_jwt = false

[functions.ai-audit]
verify_jwt = false

[functions.ai-import]
verify_jwt = false

[functions.wise-sync]
verify_jwt = false

[functions.wise-webhook]
verify_jwt = false

[functions.wise-balances]
verify_jwt = false

[functions.wise-discover]
verify_jwt = false

[functions.paypal-discover]
verify_jwt = false

[functions.paypal-sync]
verify_jwt = false

[functions.paypal-balances]
verify_jwt = false
