project_id = "bxrxrdloufobxdkdehtc"

[functions.ai-chat]
verify_jwt = false

[functions.ai-audit]
verify_jwt = false

[functions.ai-import]
verify_jwt = false

[functions.wise-sync]
verify_jwt = false

[functions.wise-webhook]
verify_jwt = false

[functions.wise-balances]
verify_jwt = false

[functions.wise-discover]
verify_jwt = false

[functions.paypal-discover]
verify_jwt = false

[functions.paypal-sync]
verify_jwt = false

[functions.paypal-balances]
verify_jwt = false

[functions.start-historical-sync]
verify_jwt = false

[functions.process-sync-chunk]
verify_jwt = false

[functions.stripe-discover]
verify_jwt = false

[functions.stripe-sync]
verify_jwt = false

[functions.stripe-balances]
verify_jwt = false

[functions.sync-scheduler]
verify_jwt = false

[functions.handle-webhook]
verify_jwt = false

[functions.airwallex-sync]
verify_jwt = false
